### ISSUE TITLE
[Feature Request] Enable Refined Gitlab on hosted solution

### ISSUE THREAD

**Issue by bennokress** [kiwicom/refined-gitlab#55]
I would like to add a self-hosted Gitlab to the list of allowed sites in the permissions. I see that there is one already pre-installed (https://gitlab.skypicker.com/*) and I would like to add more like in the Refined Github extension: 
<img width="331" alt="github" src="https://user-images.githubusercontent.com/6912918/53721309-36961280-3e63-11e9-85ad-82437696b8be.png">

**Comment by niksy** [comment]
Also looking fo this. This can be achieved with https://github.com/bfred-it/webext-domain-permission-toggle/

**Comment by Strajk** [comment]
:done: https://github.com/kiwicom/refined-gitlab/commit/1e32e37f6608280501279078e71395fda69a8b8b


thx @bennokress for good idea and @niksy for suggesting implementation :) 👏 

btw it's totally ~possible~ probable that there are some bugs and glitches,
as far as I know the extension is right now used just by few Kiwi.com devs...

Would be happy for more issues, or even PRs :)
