### ISSUE TITLE
Show docker image URL on merge requests

### ISSUE THREAD

**Issue by iakat** [kiwicom/refined-gitlab#7]
As an MVP:

hardcoded registry URL + get project url (e.g.: `frontend/frontend`) + commit hash (all of our important projects have commit hash tags) + clipboard icon.

Ugly example:
![](https://simone.sh/images/04291255_kvdux.png)

**Comment by eidam** [comment]
+1

**Comment by Strajk** [comment]
![image](https://user-images.githubusercontent.com/697301/27147426-115ed584-513d-11e7-8598-ecfa55c2135f.png)

MVP done

**Comment by Strajk** [comment]
+ configurable 
![image](https://user-images.githubusercontent.com/697301/27147455-28c019f4-513d-11e7-99e8-fabd944210e4.png)
