### ISSUE TITLE
Idea: "Remove source branch" checkbox be selected by default

### ISSUE THREAD

**Issue by jontesek** [kiwicom/refined-gitlab#8]
Just idea - can the "Remove source branch" checkbox be selected by default? I might have forgotten to click it sometimes...:)

Already discussed here I see: https://gitlab.com/gitlab-org/gitlab-ce/issues/29001

The options is gonna be in next version I guess :

**Comment by Strajk** [comment]
![image](https://cloud.githubusercontent.com/assets/697301/26489109/55df6390-4206-11e7-8784-edc41b311e84.png)
